// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gameon

import (
	"ledape.com/gameon/ent"
)

type AuthPayload struct {
	Token string    `json:"token"`
	User  *ent.User `json:"user"`
}

type GameInput struct {
	Title string `json:"title"`
	Time  string `json:"time"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignupInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
