// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gameon

import (
	"ledape.com/gameon/ent"
	"ledape.com/gameon/ent/gameparticipant"
)

type AuthPayload struct {
	RefreshToken string    `json:"refreshToken"`
	Token        string    `json:"token"`
	User         *ent.User `json:"user"`
}

type GameInput struct {
	Title string `json:"title"`
	Time  int    `json:"time"`
}

type GameResponseInput struct {
	Rsvp   gameparticipant.RsvpStatus `json:"rsvp"`
	GameID int                        `json:"gameId"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignupInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
