// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"ledape.com/gameon/ent/gameparticipant"
	"ledape.com/gameon/ent/predicate"
)

// GameParticipantDelete is the builder for deleting a GameParticipant entity.
type GameParticipantDelete struct {
	config
	hooks    []Hook
	mutation *GameParticipantMutation
}

// Where appends a list predicates to the GameParticipantDelete builder.
func (gpd *GameParticipantDelete) Where(ps ...predicate.GameParticipant) *GameParticipantDelete {
	gpd.mutation.Where(ps...)
	return gpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gpd *GameParticipantDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gpd.hooks) == 0 {
		affected, err = gpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GameParticipantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gpd.mutation = mutation
			affected, err = gpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gpd.hooks) - 1; i >= 0; i-- {
			if gpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gpd *GameParticipantDelete) ExecX(ctx context.Context) int {
	n, err := gpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gpd *GameParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: gameparticipant.Table,
		},
	}
	if ps := gpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GameParticipantDeleteOne is the builder for deleting a single GameParticipant entity.
type GameParticipantDeleteOne struct {
	gpd *GameParticipantDelete
}

// Exec executes the deletion query.
func (gpdo *GameParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := gpdo.gpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gameparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gpdo *GameParticipantDeleteOne) ExecX(ctx context.Context) {
	gpdo.gpd.ExecX(ctx)
}
