// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// GameParticipant is the predicate function for gameparticipant builders.
type GameParticipant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
