// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
